### ISSUE TITLE
 test/test_pathname.rb: test_realpath_platform: /dev/stdin does   not evaluate to ['/dev/pts/0', '/dev/proc/self/fd/0'] as realpath

### ISSUE THREAD

**Issue by mr-c** [djberg96/pathname2#2]
Hello,

In packaging the pathname2 rubygem for Debian we ran into a problem with this test while running using a tool that connect `/dev/stdin` to a pipe (example: `/dev/fd/pipe:[3729821]`) while the tests are running.

For now we have commented out the test.

**Comment by djberg96** [comment]
@mr-c Indeed, those are some dumb tests. I've refactored them and will have a new release out soon. Thanks for the report.
