### ISSUE TITLE
version number not bumped in tests for version 1.8.2

### ISSUE THREAD

**Issue by boutil** [djberg96/pathname2#6]
Hi,

I am reporting an issue against version 1.8.2, published on rubygems.org, but does not appear (yet?) here, the difference with 1.8.1 being the actual presence of the Apache license file.
Although in the library itself is bumped to 1.8.1, the version agains which it is matched in the tests is still 1.8.1, so the test fail.

**Comment by boutil** [comment]
This causes the following reported bug in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966153

**Comment by djberg96** [comment]
@boutil Fixed in 1.8.3, which also fixed some deprecation warnings. Thanks for the report!

**Comment by boutil** [comment]
thanks a lot!
